Feature/michael settimeout to battle results
timongorpg/timongo-old pull request #37
Opened 2017-03-22 11:19 UTC by MichaelKlemersson

- Add the scroll bar
- Add time out to show the battle rounds

2017-03-22 13:12 UTC, edddieee requested changes

2017-03-22 13:12 UTC, edddieee commented on gulpfile.js
> +           '../../../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js'
I think that would be a good ideia to require this file into `resources/assets/app.js` and not here.

2017-03-22 13:12 UTC, edddieee commented on resources/assets/sass/app.scss
> +@import "customscrollbar";
You should to import this file from `node_modules` folder, like this:

`@import "node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css"`

2017-03-22 13:12 UTC, eddiecode commented on resources/assets/sass/_customscrollbar.scss
> +/*
I think you should remove this file. You have already imported it.
https://github.com/timongorpg/timongo/pull/37/files#diff-1dee3aa6a79c9f1c3bf0abca2c6fd30fR12

2017-03-22 13:12 UTC, eddiecode commented on resources/views/battle-results.blade.php
> +                <!-- @foreach(array_get($log, 'fight') as $message)
If this code isn't necessary, you should remove it.

2017-03-22 13:12 UTC, eddiecode commented on gulpfile.js
> +           '../../../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js'
I think we should minify the output, before merge this PR into master.
`npm run production`

2017-03-22 13:17 UTC, MichaelKlemersson commented on resources/assets/sass/app.scss
> +@import "customscrollbar";
I think that we can't import css into scss, no?

2017-03-22 13:27 UTC, eddiecode commented on resources/assets/sass/app.scss
> +@import "customscrollbar";
You can import css normally. 😄

2017-03-22 13:32 UTC, MichaelKlemersson commented
I did it but the code wasn't imported :(



Atenciosamente,

Michael Klemersson - http://www.michaelklemersson.com

https://br.linkedin.com/in/michaelklemersson

2017-03-22 10:27 GMT-03:00 Edgar Yonemura <notifications@github.com>:

> *@eddiecode* commented on this pull request.
> ------------------------------
>
> In resources/assets/sass/app.scss
> <https://github.com/timongorpg/timongo/pull/37#discussion_r107411582>:
>
> > @@ -8,6 +8,9 @@
>  // Bootstrap
>  @import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
>
> +// Custom Scroll Bar
> +@import "customscrollbar";
>
> You can import css normally. 😄
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/timongorpg/timongo/pull/37#discussion_r107411582>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AD1SL0I8S5atOYgJvUnFF-KIPxC0-kCfks5roSGzgaJpZM4MlDOF>
> .
>

2017-03-22 14:03 UTC, MichaelKlemersson commented
PR updated :), code is minified and scroll bar is now scrolling to the last battle event :+1:

2017-03-22 14:13 UTC, eddiecode commented on resources/assets/js/app.js
> +require('../../../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min')
You forgot the `;`. 
What do you think to move this require to `bootstrap.js`?

2017-03-22 14:14 UTC, edddieee approved these changes

2017-03-22 14:37 UTC, MichaelKlemersson commented on resources/assets/js/app.js
> +require('../../../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min')
next PR :)

2017-03-22 14:49 UTC, hudsonpereira commented
I'll check this PR tonight. @eddiecode has good thoughts about it.

2017-03-22 22:54 UTC, eddiecode commented
More one thing that I forgot to say, but think that would be a good idea to fixup or squash the last two commits. Let me know if you don't know how to do this. cc @MichaelKlemersson

2017-03-22 23:22 UTC, MichaelKlemersson commented
I don't know @eddiecode how to squash for a while :(

2017-03-22 23:53 UTC, eddiecode commented
It's a very simple thing. Both squash and fixup are rebase commands to merge two or more commits. The differences is that squash don't remove the commit message.

To do a rebase you need to write the follow commands:

```
# Get the previous commit, before your PR commits.
$ git log --oneline

# Run rebase interactive command and get the last three commits (HEAD~3)
$ git rebase -i HEAD~3
```

git will open your text editor, probably vim/vi if you are using Linux or Mac.

You will see something like that:
```
pick a3240d1 add slim scroll to battle results
pick 31eb90c add scroll bar and timeout to show battle results
pick 3c18ece update import scrollbar plugin js and css

# Rebase a3240d1..3c18ece onto 3c18ece
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

And then you can squash(merge) the last two commits:

```
pick a3240d1 add slim scroll to battle results
pick 31eb90c add scroll bar and timeout to show battle results
squash 3c18ece update import scrollbar plugin js and css
```

Save the file, and the rebase will be done. 😄

2017-03-23 00:36 UTC, MichaelKlemersson commented
@eddiecode I did it, so what now?

2017-03-23 01:03 UTC, eddiecode commented
@MichaelKlemersson run `$ git log --oneline` and check if your commits were merged.
And then you just need to push your branch again: `$ git push -f your_remote_repository_name your_branch_name`

2017-03-24 11:43 UTC, MichaelKlemersson commented
I did so, I think that is ready

2017-03-24 14:12 UTC, eddiecode commented
@MichaelKlemersson for me this PR it's ok. Can you check it later @hudsonpereira?

2017-03-24 21:11 UTC, merged